title: Chuck Hoffman
description: "Another programmer blog, lucky you."
disclaimer: "Note: not affiliated with \"hoff2\" on wordpress.com. Gross."

# put your disqus here
disqus_shortname: centipedefarmer
reading_time: false # if true, shows the estimated reading time for a post
#words_per_minute: 200
logo: images/logo.png # logo visible in the topbar
excerpt_separator: '<!--more-->'

# Your site's domain goes here (eg: //mmistakes.github.io,
# http://mademistakes.com, etc) When testing locally leave blank or use
# http://localhost:4000
url: https://hoff2.dev

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  #- title: 'Favorites'
  #  url: '#'
  #  submenu:
  #    - title: 'Code Highlighter'
  #      url: '/intro/code-highlighting-post/'
  #    - title: 'Sample Post'
  #      url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           Chuck Hoffman
  site:           https://hoff2.dev
  avatar:         images/avatar.jpg
  bio: >-
    I'm from Iowa. I sling code for a living and get pretty into it.
    I also do some fun things with experimental music and retro-tech.
  email:          centipedefarmer@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: hoff2dev
  # GitHub nick for use in follow button in author block.
  github: hoff2

# Twitter account associated with the site if different from owner/author
# twitter account. Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and
# remove as you like.
social:
  - title: "github"
    url: "https://github.com/hoff2"
  - title: "linkedin"
    url: "https://linkedin.com/in/hoff2"
  - title: "twitter"
    url: "https://twitter.com/hoff2dev"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-paginate

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:year-:month-:day-:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    line_numbers: false
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
