title: Chuck Hoffman
description: "Another programmer blog, lucky you."
disclaimer: "Note: not affiliated with \"hoff2\" on wordpress.com. Gross."

reading_time: false # if true, shows the estimated reading time for a post
excerpt_separator: '<!--more-->'

url: https://hoff2.dev

menu:
  - title: 'Home'
    url: '/'
  - title: 'About'
    url: '/about'
  - title: 'Tags'
    url: '/tags'
  #- title: 'Categories'
  #  url: '/categories'
  #  type: 'categories'
  #- title: 'Favorites'
  #  url: '#'
  #  submenu:
  #    - title: 'Code Highlighter'
  #      url: '/intro/code-highlighting-post/'
  #    - title: 'Sample Post'
  #      url: '/intro/sample-post/'

owner:
  name:           Chuck Hoffman
  site:           https://hoff2.dev
  avatar:         images/avatar.jpg
  bio: >-
    I'm from Iowa. I sling code for a living and get pretty into it.
    I also do some fun things with experimental music and retro-tech.
  email:          centipedefarmer@gmail.com
  twitter: hoff2dev
  github: hoff2

# Social networking links used in author block underneath posts. Update and
# remove as you like.
social:
  - title: "github"
    url: "https://github.com/hoff2"
  - title: "linkedin"
    url: "https://linkedin.com/in/hoff2"
  - title: "twitter"
    url: "https://twitter.com/hoff2dev"

timezone:    America/Chicago
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-paginate

permalink:   /:categories/:year-:month-:day-:title/

paginate: 5

float_share: false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    line_numbers: false
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: false

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
